# This file is automatically generated by pyo3_stub_gen

import enum
import typing

from nautilus_trader import model

__all__ = [
    "BinanceDataClientConfig",
    "BinanceDataClientFactory",
    "BinanceEnvironment",
    "BinanceExecClientConfig",
    "BinanceExecutionClientFactory",
    "BinancePositionSide",
    "BinanceProductType",
]

@typing.final
class BinanceDataClientConfig:
    def __init__(
        self,
        product_types: typing.Sequence[BinanceProductType] | None = ...,
        environment: BinanceEnvironment | None = ...,
        base_url_http: str | None = ...,
        base_url_ws: str | None = ...,
        api_key: str | None = ...,
        api_secret: str | None = ...,
        instrument_status_poll_secs: int | None = ...,
    ) -> None: ...

@typing.final
class BinanceDataClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class BinanceExecClientConfig:
    def __init__(
        self,
        trader_id: model.TraderId,
        account_id: model.AccountId,
        product_types: typing.Sequence[BinanceProductType] | None,
        environment: BinanceEnvironment | None,
        base_url_http: str | None,
        base_url_ws: str | None,
        base_url_ws_trading: str | None,
        use_ws_trading: bool,
        api_key: str | None = ...,
        api_secret: str | None = ...,
    ) -> None: ...

@typing.final
class BinanceExecutionClientFactory:
    def __init__(self) -> None: ...
    def name(self) -> str: ...

@typing.final
class BinanceEnvironment(enum.Enum):
    Mainnet = ...
    Testnet = ...
    Demo = ...

@typing.final
class BinancePositionSide(enum.Enum):
    Both = ...
    Long = ...
    Short = ...
    Unknown = ...

@typing.final
class BinanceProductType(enum.Enum):
    Spot = ...
    Margin = ...
    UsdM = ...
    CoinM = ...
    Options = ...
