# This file is automatically generated by pyo3_stub_gen

import enum
import typing

__all__ = [
    "PolymarketDataClientConfig",
    "PolymarketExecClientConfig",
    "SignatureType",
]

@typing.final
class PolymarketDataClientConfig:
    def __init__(
        self,
        base_url_http: str | None = ...,
        base_url_ws: str | None = ...,
        base_url_gamma: str | None = ...,
        base_url_data_api: str | None = ...,
        http_timeout_secs: int | None = ...,
        ws_timeout_secs: int | None = ...,
        ws_max_subscriptions: int | None = ...,
        update_instruments_interval_mins: int | None = ...,
    ) -> None: ...

@typing.final
class PolymarketExecClientConfig:
    def __init__(
        self,
        trader_id: str | None = ...,
        account_id: str | None = ...,
        private_key: str | None = ...,
        api_key: str | None = ...,
        api_secret: str | None = ...,
        passphrase: str | None = ...,
        funder: str | None = ...,
        signature_type: SignatureType | None = ...,
        base_url_http: str | None = ...,
        base_url_ws: str | None = ...,
        base_url_gamma: str | None = ...,
        http_timeout_secs: int | None = ...,
        max_retries: int | None = ...,
        retry_delay_initial_ms: int | None = ...,
        retry_delay_max_ms: int | None = ...,
        ack_timeout_secs: int | None = ...,
    ) -> None: ...

@typing.final
class SignatureType(enum.Enum):
    Eoa = ...
    PolyProxy = ...
    PolyGnosisSafe = ...
